### ISSUE TITLE
Please create a readme for this shiny new repository

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#1]
Please implement a shine new readme

**Comment by fundrequest-notifier** [comment]
Great! 1 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 1 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great, this issue is now funded on FundRequest: https://alpha.fundrequest.io!  1 FND was funded on 2017-12-22

**Comment by fundrequest-notifier** [comment]
Great, this issue is now funded on FundRequest: https://alpha.fundrequest.io!  

1 FND was funded on 2017-12-22

**Comment by fundrequest-notifier** [comment]
Great, this issue is now funded on FundRequest: https://alpha.fundrequest.io!  

1 FND was funded on 2017-12-22
