### ISSUE TITLE
trying to trigger the error msg

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#110]

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/39/badge)](https://dev-web.fundrequest.io/requests/39) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/39).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
