### ISSUE TITLE
Create my own Area51-issue for testing the alpha-MVP (V2)

### ISSUE THREAD

**Issue by ghost** [FundRequest/area51#12]

**Comment by fundrequest-notifier** [comment]
Great! Nico Haelterman funded 1.0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Info FundRequest funded 0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Info FundRequest funded 0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Info Gentse Tenten funded 62 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 2 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 2 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/61/badge)](https://dev-web.fundrequest.io/requests/61) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/61).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
