### ISSUE TITLE
Issue 301-2

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/area51#123]

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/55/badge)](https://dev-web.fundrequest.io/requests/55) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #123`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/55/badge)](http://localhost:8080/requests/55) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](http://localhost:8080/requests/55).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
