### ISSUE TITLE
Test-349

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#145]

**Comment by fundrequest-notifier** [comment]
[![](https://staging.fundrequest.io/requests/9/badge)](https://staging.fundrequest.io/requests/9) [![](https://staging.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://staging.fundrequest.io/requests/9). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #145`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
