### ISSUE TITLE
Comment link update

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#149]

**Comment by fundrequest-notifier** [comment]
[![](https://staging.fundrequest.io/requests/11/badge)](https://staging.fundrequest.io/requests/11) [![](https://staging.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://staging.fundrequest.io/requests/11). A developer can claim [the reward](https://staging.fundrequest.io/requests/11) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #149`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
