### ISSUE TITLE
a new issue

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/area51#167]
TEsting all the `details`

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/84/badge)](http://localhost:8080/requests/84) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/84). A developer can claim [the reward](http://localhost:8080/requests/84) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #167`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
