### ISSUE TITLE
Test 487

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/area51#178]

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/91/badge)](https://tst1-web.fundrequest.io/requests/91) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://tst1-web.fundrequest.io/requests/91). A developer can claim [the reward](https://tst1-web.fundrequest.io/requests/91) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #178`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/11/badge)](http://localhost:8080/requests/11) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/11). A developer can claim [the reward](http://localhost:8080/requests/11) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #178`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/11/badge)](http://localhost:8080/requests/11) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. [The reward](http://localhost:8080/requests/11) linked to this issue has been transferred to your account.
* Payment details can be tracked on [Etherscan](https://kovan.etherscan.io/tx/0xbc00ec21e555aaf6115a158683986d8fd77dde3c00fd42b2ce5d6ceba7f94936)
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
