### ISSUE TITLE
Test 487-1

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/area51#180]

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/92/badge)](https://tst1-web.fundrequest.io/requests/92) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://tst1-web.fundrequest.io/requests/92). A developer can claim [the reward](https://tst1-web.fundrequest.io/requests/92) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #180`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/92/badge)](https://tst1-web.fundrequest.io/requests/92) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. [The reward](https://tst1-web.fundrequest.io/requests/92) linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/12/badge)](http://localhost:8080/requests/12) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/12). A developer can claim [the reward](http://localhost:8080/requests/12) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #180`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/12/badge)](http://localhost:8080/requests/12) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. [The reward](http://localhost:8080/requests/12) linked to this issue has been transferred to your account.
* Payment details can be tracked on [Etherscan](https://kovan.etherscan.io/tx/0xea78592c528faca322f783e08bec9a85a9a91b23d4474728eea7e0e3d00b633a)
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
