### ISSUE TITLE
Test #515

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/area51#210]

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/1088/badge)](http://localhost:8080/requests/1088) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/1088). A developer can claim [the reward](http://localhost:8080/requests/1088) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #210`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/1088/badge)](http://localhost:8080/requests/1088) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim [the reward](http://localhost:8080/requests/1088) that is linked to this issue. This can be done directly from the [funded request](http://localhost:8080/requests/1088).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/28/badge)](http://localhost:8080/requests/28) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/28). A developer can claim [the reward](http://localhost:8080/requests/28) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #210`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by marc0olo** [comment]
[![](http://localhost:8080/requests/28/badge)](http://localhost:8080/requests/28) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. [The reward](http://localhost:8080/requests/28) linked to this issue has been transferred to your account.
* Payment details can be tracked on [Etherscan](https://kovan.etherscan.io/tx/0xe4484691949fc2cb8aa86ab858cc1522c25ccebfd61cd617a84d9ad33b33f33d)
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
