### ISSUE TITLE
Create and Fund FundRequest Issue

### ISSUE THREAD

**Issue by ghost** [FundRequest/area51#22]

**Comment by fundrequest-notifier** [comment]
Great! Nico Haelterman funded 2 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 3 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 3 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.
