### ISSUE TITLE
testing pull request 524

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#220]
testing PR 524

**Comment by fundrequest-notifier** [comment]
[![](https://tst1.fundrequest.io/requests/100/badge)](https://tst1.fundrequest.io/requests/100) [![](https://tst1.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://tst1.fundrequest.io/requests/100). A developer can claim [the reward](https://tst1.fundrequest.io/requests/100) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #220`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1.fundrequest.io/requests/100/badge)](https://tst1.fundrequest.io/requests/100) [![](https://tst1.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim [the reward](https://tst1.fundrequest.io/requests/100) that is linked to this issue. This can be done directly from the [funded request](https://tst1.fundrequest.io/requests/100).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
