### ISSUE TITLE
Check for initial state of a FundRequestIssue

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/area51#28]

**Comment by fundrequest-notifier** [comment]
Great! KAY BROWN funded 5 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 1 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 1 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.
