### ISSUE TITLE
Re-testing the alpha

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/area51#33]

**Comment by fundrequest-notifier** [comment]
Great! Anonymous funded 0.1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Anonymous funded 3 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 33 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 33 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.
