### ISSUE TITLE
Re-testing the alpha 2

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/area51#34]

**Comment by fundrequest-notifier** [comment]
Great! Anonymous funded 2 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Anonymous funded 0.6 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 4 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 4 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.
