### ISSUE TITLE
Fund a FundRequestIssue

### ISSUE THREAD

**Issue by ghost** [FundRequest/area51#5]

**Comment by fundrequest-notifier** [comment]
Great! Nico Haelterman funded 5 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Dimitris Baltas funded 30 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 2 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 20 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Joris Van den Bogaert funded 1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Quinten De Swaef funded 2 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Nico Haelterman funded 1 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Andrei Karpushonak funded 0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Andrei Karpushonak funded 0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Andrei Karpushonak funded 10 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by karelstriegel** [comment]
Dear Andrei, please join our slack so we can transfer you Rinkeby FND tokens in order for you to test the platform (https://slack.fundrequest.io)
