### ISSUE TITLE
add hello world for python

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/area51#52]

**Comment by fundrequest-notifier** [comment]
Great! 6 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/11/badge)](https://tst1-web.fundrequest.io/requests/11) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim [the reward](https://tst1-web.fundrequest.io/requests/11) that is linked to this issue. This can be done directly from the [funded request](https://tst1-web.fundrequest.io/requests/11).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
