### ISSUE TITLE
Create a new issue for testing

### ISSUE THREAD

**Issue by mrsinguyen** [FundRequest/area51#55]
### Expected behavior

- Created the issue successfully in github

### Steps to reproduce the behavior

1. Create a new issue
2. Go to https://alpha.fundrequest.io/#/requests to add a new request
3. Go to https://alpha.fundrequest.io/#/home to check the request
4. Go to https://alpha.fundrequest.io/#/requests/27 to add fund

**Comment by fundrequest-notifier** [comment]
Great! 2 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! 2 FND was added to this issue. For more information, go to https://alpha.fundrequest.io.

**Comment by mrsinguyen** [comment]
Close issue to test
