### ISSUE TITLE
Nico Retest 20180204

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/area51#71]

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/30/badge)](https://dev-web.fundrequest.io/requests/30) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nicohaelterman for your code contribution. The reward linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
