### ISSUE TITLE
Issue to demo Trust Wallet integration

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#72]

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/33/badge)](https://dev-web.fundrequest.io/requests/33) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #33`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/33/badge)](https://dev-web.fundrequest.io/requests/33) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
Thank you @karelstriegel for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/33).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
