### ISSUE TITLE
Nico retest 20180304

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/area51#74]

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/15/badge)](http://localhost:8080/requests/15) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #15`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* For better GitHub integration please install the FundRequest [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/15/badge)](http://localhost:8080/requests/15) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #15`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* For better GitHub integration please install the FundRequest [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
