### ISSUE TITLE
Boccaccio Release test issue #2

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#79]
### Expected behaviour
That everythings works perfectly

### Actual behaviour
Some bugs where found 

### Steps to reproduce the behaviour
Follow step 1 , 2 and 3: 
- Step1
- Step2
- Step3

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/32/badge)](https://dev-web.fundrequest.io/requests/32) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #32`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/41/badge)](https://tst1-web.fundrequest.io/requests/41) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Qkyrie for your code contribution. You can now claim [the reward](https://tst1-web.fundrequest.io/requests/41) that is linked to this issue. This can be done directly from the [funded request](https://tst1-web.fundrequest.io/requests/41).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
