### ISSUE TITLE
How to comment when a request is resolved (claimable)

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#87]
[![](https://img.shields.io/badge/funding%20status-resolved%20(%2016,183%20FND)-3cdafc.svg)](https://dev-web.fundrequest.io/requests/1) [![](https://img.shields.io/badge/powered%20by-FundRequest-yellow.svg)](https://fundrequest.io) <a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>

Thank you @davyvanroy for your code contribution. You can now claim the reward that is linked to this issue.  This can be done via our [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest).  our directly from the [funded request](https://dev-web.fundrequest.io/requests/1). 

* For better GitHub integration please install the FundRequest [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest). 
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/25/badge)](http://localhost:8080/requests/25) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #25`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* For better GitHub integration please install the FundRequest [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/25/badge)](http://localhost:8080/requests/25) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)<a href="https://fundrequest.io"><img align="right" src="https://avatars0.githubusercontent.com/u/22447793?s=20&v=4"></a>
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done via our [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest) or directly from the [funded request](http://localhost:8080/requests/25).

* For better GitHub integration please install the FundRequest [Chome browser plugin](https://chrome.google.com/webstore/search/fundrequest).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
