### ISSUE TITLE
Bocca test 04/05 C

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/area51#92]

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/18/badge)](https://dev-web.fundrequest.io/requests/18) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. The reward linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/27/badge)](http://localhost:8080/requests/27) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. [The reward](http://localhost:8080/requests/27) linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
